export const apiRoutes = {
  getTokenByPassword: `/api/login`,
  getTokenByRefresh: `/api/refresh_token`,
  getProfile: `/api/getProfile`,
  user: `/api/users/:id?`,
  getRolesList: `/api/roles`,
  getOperationList: `/api/status_operations`,
  getPlcIndication: `/api/plc/indication`,
  getDBIndication: `/api/actuator/health/db`,
  addressPlc: `/api/plc/address/:id?`,
  reference: `/api/references/:id?`,
  recipe: `/api/recipe/:id?`,
  recipeGraph: `/api/recipe_graph/:id?`,
  referenceListName: `/api/references/list`,
  operation: `/api/operations/:id?`,
  part: `/api/parts/:id?`,
  graphResultReal: `/api/graph_results_real`,
  graphResultBoolean: `/api/graph_results_boolean`,
  getTypeOpc: `/api/typesOpc`,
  getUnit: `/api/units`,
  tagResults: `/api/tags_result/:id?`,
  operationResults: `/api/operation_result/:id?`,
  downloadOperationsCsv: `/api/download_operations_csv`,
  downloadPartsCsv: `/api/download_parts_csv`,
  graphResultEffort: `/api/graph_results_effort`,
  graphResultMoment: `/api/graph_results_moment`,
  referencePartName: `/api/references/part/name`,
};

export const pageRoutes = {
  main: '/',
  auth: '/auth',
  user: '/user',
  appointment: '/appointment/:id',
};
